### ISSUE TITLE
Add #StandWithUkraine banner

### ISSUE THREAD

**Issue by Flashboyv2** [Virbos/virbos-iso#7]
How about adding #StandWithUkraine banner?
https://github.com/vshymanskyy/StandWithUkraine
https://stand-with-ukraine.pp.ua/
![StandWithUkraine](https://github.com/Virbos/virbos-iso/assets/85509544/f4d2ce1a-e1d6-43fc-80b0-afd7e71fc431)
![banner2-direct](https://github.com/Virbos/virbos-iso/assets/85509544/0c51df89-970a-424e-8521-d87a5209f168)

**Comment by jtbx** [comment]
No
